//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LrcEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LrcEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;LColorConfig&gt;
        ///    &lt;ColorSet&gt;    
        ///        &lt;Color name=&quot;red50&quot;&gt;#fde0dc&lt;/Color&gt;
        ///        &lt;Color name=&quot;red100&quot;&gt;#f9bdbb&lt;/Color&gt;
        ///        &lt;Color name=&quot;red200&quot;&gt;#f69988&lt;/Color&gt;
        ///        &lt;Color name=&quot;red300&quot;&gt;#f36c60&lt;/Color&gt;
        ///        &lt;Color name=&quot;red400&quot;&gt;#e84e40&lt;/Color&gt;
        ///        &lt;Color name=&quot;red500&quot;&gt;#e51c23&lt;/Color&gt;
        ///        &lt;Color name=&quot;red600&quot;&gt;#dd191d&lt;/Color&gt;
        ///        &lt;Color name=&quot;red700&quot;&gt;#d01716&lt;/Color&gt;
        ///        &lt;Color name=&quot;red800&quot;&gt;#c41411&lt;/Color&gt;
        ///        &lt;Color name=&quot;red900&quot;&gt;#b0120a&lt;/Co [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ColorConfig {
            get {
                return ResourceManager.GetString("ColorConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 var b = function (a, b) {
        ///    for (var d = 0; d &lt; b.length - 2; d += 3) {
        ///        var c = b.charAt(d + 2),
        ///            c = &quot;a&quot; &lt;= c ? c.charCodeAt(0) - 87 : Number(c),
        ///            c = &quot;+&quot; == b.charAt(d + 1) ? a &gt;&gt;&gt; c : a &lt;&lt; c;
        ///        a = &quot;+&quot; == b.charAt(d) ? a + c &amp; 4294967295 : a ^ c
        ///    }
        ///    return a
        ///}
        /// 
        ///var tk =  function (a,TKK) {
        ///    for (var e = TKK.split(&quot;.&quot;), h = Number(e[0]) || 0, g = [], d = 0, f = 0; f &lt; a.length; f++) {
        ///        var c = a.charCodeAt(f);
        ///        128 &gt; c ? g[d++] = c [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string JSCode {
            get {
                return ResourceManager.GetString("JSCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap slogo {
            get {
                object obj = ResourceManager.GetObject("slogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [songName: Look At Me Now]
        ///[Artists: Chalie Puth]
        ///[Album: Ego]
        ///[00:10.16]I said this time next year
        ///[00:10.16]我说过明年今日
        ///[00:12.27]I’m gonna be the one to do
        ///[00:12.27]我将改变自己并做到
        ///[00:13.63]Everything and more you said I couldn’t do
        ///[00:13.63]所有你说和没说我做不到的事情
        ///[00:17.69]This one is for you
        ///[00:17.69]听好，这是对你说的
        ///[00:20.68]This time next year
        ///[00:20.68]明年今日
        ///[00:22.39]I’m gonna be stronger
        ///[00:22.39]我要变更强壮一点
        ///[00:23.52]A little bit taller
        ///[00:23.52]更高挑一点
        ///[00:24.88]Top is my only view
        ///[00:24.88]眼光放的最高
        ///[ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string TestLrc {
            get {
                return ResourceManager.GetString("TestLrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;LThemeConfig&gt;
        ///    &lt;ThemeSet&gt;
        ///        &lt;theme name=&quot;Teal&quot;&gt;
        ///            &lt;PrimaryColor value=&quot;#009688&quot;/&gt;
        ///            &lt;SecondaryColor value=&quot;#00BFA5&quot;/&gt;
        ///        &lt;/theme&gt;
        ///        &lt;theme name=&quot;Light Blue&quot;&gt;
        ///            &lt;PrimaryColor value=&quot;#03A9F4&quot;/&gt;
        ///            &lt;SecondaryColor value=&quot;#0091EA&quot;/&gt;
        ///        &lt;/theme&gt;
        ///        &lt;theme name=&quot;Cyan&quot;&gt;
        ///            &lt;PrimaryColor value=&quot;#00BCD4&quot;/&gt;
        ///            &lt;SecondaryColor value=&quot;#00B8D4&quot;/&gt;
        ///        &lt;/theme&gt;
        ///        &lt;theme name=&quot;Red&quot;&gt;
        ///       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        public static string ThemeConfig {
            get {
                return ResourceManager.GetString("ThemeConfig", resourceCulture);
            }
        }
    }
}
